### ISSUE TITLE
ATCNet accuracy

### ISSUE THREAD

**Issue by HaneenSu** [NgHanWei/SSTACNet#1]
Hi

I noticed that you are quoting an accuracy of 81.15 for ATCNet, however, their paper quotes an accuracy of 85% which is equal to your model's accuracy. How is this possible?
https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9852687

**Comment by NgHanWei** [comment]
Hi Haneen thank you for your question!

Indeed their paper quoted 85% however the results reported had data leakage issues whereby the test set was also used as validation set, which later they reported a proper test accuracy of 81.10% as shown in their github link.

https://github.com/Altaheri/EEG-ATCNet
