### ISSUE TITLE
Where is the model?

### ISSUE THREAD

**Issue by HaneenSu** [NgHanWei/SSTACNet#2]
Hello,

I was interested in testing your model with a dataset I collected but I wasn't able to find the model code (it is not part of models.py). Any help?

Thanks
Haneen

**Comment by NgHanWei** [comment]
Hi,

The classifcation model backbone follows ATCNet found in models.py, the proposed framework may be found in the main_TrainValTest.py file, finally the VAE model proposed and used in this study is found in vae.py, thank you!
